In [16]:
import numpy as np

### Challenge 1.2


In [150]:
def pairwise_product_fast(a):
    result = 0
    # find first max
    index_1 = 0
    for i in range(len(a)):
        if a[i] > a[index_1]:
            index_1 = i
    # if first element is max, look for next max from index 1 onwards 
    if index_1 == 0:
        index_2 = 1
    else:
        index_2 = 0
    #print(index_1, index_2)
    for i in range(len(a)):
        # if current value is greater than current index_2 value
        # if current value is not equal to index_1 value
        if a[i] > a[index_2] and i != index_1:
            index_2 = i
    return a[index_1] * a[index_2]

def pairwise_product_naive(a):
    result = 0
    n = len(a)
    for i in range(n):
        for j in range(i+1, n):
            if a[i]*a[j] > result:
                result = a[i]*a[j]
    return result
print(pairwise_product_fast([0, 1, 0, 0]))
print(pairwise_product_naive([0, 1, 0, 0]))

0
0


In [151]:
def stress_test(N, M):
    """
    Stress testing of the maximum pairwise product algorithms.
    
    Parameters
    ----------
    N : int
        Maximum length of array, in each iteration a random number
        between 2 and N is drawn to set the array length.
    M : int
        Maximum value of the numbers in array, each array contains numbers
        between 0 and M.
    
    Return
    ------
    result_1, result_2 : int, int
        Naive and fast answers from the mismatch
    """
    passed = True
    while passed:
        n = np.random.randint(2, N)
        a = np.random.randint(0, M, n)
        result_1 = pairwise_product_naive(a)
        result_2 = pairwise_product_fast(a)
        print(a)
        if result_1 == result_2:
            print("OK")
        else:
            print("Wrong Answer")
            passed = False
    return result_1, result_2


In [139]:
#stress_test(10, 100000)

In [140]:
a = [95735, 83508, 39820, 53567, 24963, 83755, 40554, 95735, 80268]
print(pairwise_product_fast(a))
print(pairwise_product_naive(a))

8018284925
9165190225


In [152]:
naive, fast = stress_test(5, 9)
print(naive, fast)

[2 0 1]
OK
[5 2]
OK
[5 3 5]
OK
[5 1 4 1]
OK
[1 2 3]
OK
[3 8]
OK
[3 6 5]
OK
[8 1 5 7]
OK
[1 3]
OK
[6 6 3 6]
OK
[0 2 5 5]
OK
[3 2 2 5]
OK
[7 5]
OK
[3 8 5 1]
OK
[3 2 5]
OK
[0 2 2]
OK
[4 8 6 8]
OK
[4 3]
OK
[4 5 8]
OK
[1 3 6 6]
OK
[8 0 5]
OK
[6 5]
OK
[3 3 8 7]
OK
[5 4 2 3]
OK
[0 2 4]
OK
[3 6]
OK
[3 1 4]
OK
[0 6]
OK
[3 3 0 7]
OK
[6 7 1]
OK
[8 7]
OK
[8 7 7 7]
OK
[2 0 1 6]
OK
[3 1]
OK
[3 6 2]
OK
[1 1]
OK
[4 7 8]
OK
[3 3 3 6]
OK
[5 8 3 6]
OK
[3 5 4 5]
OK
[0 4 5]
OK
[2 3 4 8]
OK
[8 4 3 2]
OK
[6 3 4]
OK
[8 1 8]
OK
[1 8 8]
OK
[3 7]
OK
[5 4 3]
OK
[1 6]
OK
[6 5 6 5]
OK
[5 5 2 1]
OK
[8 6]
OK
[6 3 0 6]
OK
[4 3 5 7]
OK
[7 8 5]
OK
[4 4]
OK
[6 8 6]
OK
[0 5]
OK
[5 5]
OK
[8 4]
OK
[1 1 1 3]
OK
[6 1 3 1]
OK
[8 3]
OK
[8 6 2]
OK
[2 7]
OK
[3 8 7]
OK
[6 0 2 6]
OK
[4 7]
OK
[5 6 0]
OK
[8 4]
OK
[6 3 8 4]
OK
[6 4 1]
OK
[0 8]
OK
[3 5]
OK
[0 3]
OK
[2 1 5 4]
OK
[0 2 6 6]
OK
[4 7]
OK
[4 4 6 4]
OK
[4 4 1 7]
OK
[3 0 1 7]
OK
[6 4]
OK
[2 8]
OK
[3 0]
OK
[6 5 4]
OK
[7 7 1 0]
OK
[3 5 0]
OK
[5 6]
OK
[6 5]
OK
[6 7 6 4]
OK
[0 4]


[2 4]
OK
[3 7 1 7]
OK
[7 2 6]
OK
[5 2]
OK
[0 0 2]
OK
[6 8]
OK
[4 4]
OK
[6 5 5 2]
OK
[7 2 7 5]
OK
[2 7 5]
OK
[0 2 4 3]
OK
[8 2 5 7]
OK
[5 3]
OK
[2 0]
OK
[6 6 3 3]
OK
[0 0 2]
OK
[2 2 3]
OK
[6 1 1 7]
OK
[0 8 5 5]
OK
[7 6]
OK
[0 8 1 1]
OK
[1 1 1 8]
OK
[4 4]
OK
[4 7 7]
OK
[1 8 8 3]
OK
[0 4 8 5]
OK
[4 5]
OK
[4 7]
OK
[2 0]
OK
[2 7 1]
OK
[2 3]
OK
[1 5 0 5]
OK
[8 4 8 5]
OK
[7 5 1]
OK
[1 7 2]
OK
[6 8 4]
OK
[8 6]
OK
[1 2]
OK
[8 5 0]
OK
[0 3 4 2]
OK
[1 2 6 4]
OK
[0 3 5 0]
OK
[6 6 3 7]
OK
[6 8 8]
OK
[2 4]
OK
[4 8 2 5]
OK
[2 2 8]
OK
[5 7 2 4]
OK
[2 4 8 4]
OK
[7 0 4]
OK
[1 8 0 4]
OK
[2 4 5 0]
OK
[3 5 4]
OK
[4 7 3]
OK
[5 4]
OK
[0 1]
OK
[0 2 1]
OK
[4 5 1]
OK
[1 7]
OK
[6 6 3 3]
OK
[3 1]
OK
[7 3 4]
OK
[0 3 5 1]
OK
[0 7 2]
OK
[1 4 1]
OK
[5 4]
OK
[3 5]
OK
[3 3]
OK
[0 1 7 4]
OK
[7 0]
OK
[6 3 7]
OK
[0 3 1]
OK
[5 0]
OK
[5 2 4 7]
OK
[3 0 1]
OK
[2 2]
OK
[4 5 4 2]
OK
[3 5 7 0]
OK
[1 4 4 5]
OK
[2 4 5 6]
OK
[3 3]
OK
[3 2 5]
OK
[8 8]
OK
[3 2 6 4]
OK
[4 3 5 6]
OK
[7 8 7]
OK
[1 2 6 0]
OK
[4 5]
OK
[2 3 6]
OK
[6 8 0]
O

OK
[7 7 8 8]
OK
[1 4 6]
OK
[6 7 7]
OK
[7 5 7 4]
OK
[7 5]
OK
[3 2 0]
OK
[8 4]
OK
[2 3 5 5]
OK
[3 6]
OK
[1 8 8 8]
OK
[2 8 8]
OK
[0 4 2]
OK
[2 6 5]
OK
[8 4]
OK
[4 4]
OK
[6 6]
OK
[7 6]
OK
[3 8 1]
OK
[1 5 0]
OK
[0 8 0]
OK
[5 7 1]
OK
[4 4 3 8]
OK
[2 8 6 0]
OK
[1 2 5 5]
OK
[0 8 5]
OK
[4 3 7]
OK
[0 5]
OK
[6 1 7 0]
OK
[3 8 7 5]
OK
[6 2 0 8]
OK
[1 4 6 0]
OK
[0 3 6 3]
OK
[3 3 5]
OK
[1 0 5]
OK
[5 7]
OK
[8 8 0]
OK
[2 6 6 7]
OK
[3 7 5 2]
OK
[2 7]
OK
[6 4 2 4]
OK
[1 1 8 7]
OK
[4 0 5 6]
OK
[0 7]
OK
[1 4]
OK
[5 6]
OK
[6 7]
OK
[8 3]
OK
[2 7 4]
OK
[0 5]
OK
[6 8 1]
OK
[3 4 2 1]
OK
[2 7 0]
OK
[2 0]
OK
[3 4 4]
OK
[3 4]
OK
[1 2]
OK
[7 1]
OK
[7 4]
OK
[1 4 5 4]
OK
[0 7 4 8]
OK
[5 5]
OK
[4 1 5]
OK
[3 2]
OK
[3 7 7 3]
OK
[7 8 2 0]
OK
[7 5 2]
OK
[8 0]
OK
[3 7 3]
OK
[2 5 0]
OK
[1 1 6 8]
OK
[8 0 8]
OK
[6 8 6]
OK
[7 5]
OK
[1 1 1]
OK
[1 7 7]
OK
[5 3]
OK
[4 2]
OK
[0 7 1 3]
OK
[1 7]
OK
[3 1]
OK
[8 3 1 3]
OK
[0 7 1 2]
OK
[5 8]
OK
[6 5 1 5]
OK
[7 3 7 3]
OK
[8 4 6]
OK
[4 8 6 1]
OK
[0 0 8]
OK
[0 5 2]
OK
[0 1]
OK
[7 7 6 2]
O

OK
[2 5 8 6]
OK
[7 2]
OK
[1 7 6]
OK
[3 4]
OK
[4 5]
OK
[0 8 7 6]
OK
[4 2 1 2]
OK
[5 1]
OK
[5 1]
OK
[3 0 1]
OK
[0 5 4]
OK
[4 3]
OK
[8 8 2]
OK
[3 5 2]
OK
[1 7 6 8]
OK
[4 8 0 1]
OK
[3 0 5]
OK
[5 6 5 1]
OK
[7 1 5 4]
OK
[4 3]
OK
[4 6]
OK
[4 6 7 2]
OK
[8 4 0 8]
OK
[0 7 3]
OK
[3 3]
OK
[6 1 2]
OK
[7 6 3 2]
OK
[6 3 7 1]
OK
[7 8 2 0]
OK
[2 4]
OK
[7 2 5 8]
OK
[1 3 7 3]
OK
[6 0]
OK
[5 8 0 0]
OK
[2 2]
OK
[1 1 8 6]
OK
[6 1]
OK
[1 0 3]
OK
[3 5]
OK
[3 6]
OK
[3 3 2 6]
OK
[4 1 7]
OK
[5 5 7 5]
OK
[2 1 0]
OK
[3 4 8]
OK
[3 5 5 4]
OK
[3 8 3]
OK
[8 1 5]
OK
[2 7]
OK
[2 3]
OK
[3 6]
OK
[2 5]
OK
[4 4 7]
OK
[8 2 3 0]
OK
[2 4]
OK
[0 6 7]
OK
[4 0 1]
OK
[4 4 2 7]
OK
[3 4]
OK
[4 3 3]
OK
[1 1]
OK
[2 7 2 7]
OK
[7 5 5]
OK
[0 8 4 5]
OK
[7 4 4 6]
OK
[8 8 7]
OK
[3 8 4 2]
OK
[1 4]
OK
[2 2 1 8]
OK
[5 4 3 1]
OK
[5 5]
OK
[0 7]
OK
[6 1 8]
OK
[1 6 6 6]
OK
[5 8 1 2]
OK
[5 6]
OK
[1 4 3]
OK
[4 6 2]
OK
[5 6]
OK
[6 0]
OK
[4 1]
OK
[5 8 5]
OK
[3 2]
OK
[2 2]
OK
[1 7 6 8]
OK
[2 5]
OK
[2 1 6 7]
OK
[0 8 0]
OK
[4 0]
OK
[7 0 7 3]
OK
[5 4 6]
O

[3 0 3]
OK
[0 6 2 3]
OK
[5 4 5 4]
OK
[4 6 0 8]
OK
[5 8 8]
OK
[1 5 0]
OK
[1 7 4 3]
OK
[6 8]
OK
[5 8 2 6]
OK
[7 4]
OK
[3 4 0 4]
OK
[7 1]
OK
[4 4 4]
OK
[0 2 5]
OK
[7 6 6 0]
OK
[6 5 0]
OK
[1 2 7 7]
OK
[6 4 4]
OK
[7 2 6 4]
OK
[1 4 3 8]
OK
[1 5 2]
OK
[2 1 8]
OK
[7 5 6 8]
OK
[2 8 2]
OK
[6 1 1 0]
OK
[3 4 5 5]
OK
[6 2]
OK
[1 2 8]
OK
[5 8 1]
OK
[2 3 2]
OK
[7 4 5 7]
OK
[1 2 6 3]
OK
[0 1 5]
OK
[8 1 3]
OK
[4 3]
OK
[0 2]
OK
[7 4 0]
OK
[2 7]
OK
[3 6 6 1]
OK
[0 1 2]
OK
[6 2 0 7]
OK
[8 3]
OK
[2 2]
OK
[0 7 5]
OK
[3 0]
OK
[4 3 8]
OK
[1 7 1 1]
OK
[3 3 6]
OK
[5 7 7]
OK
[5 1]
OK
[4 1 4 7]
OK
[4 0]
OK
[4 1]
OK
[1 3 3 2]
OK
[4 6]
OK
[1 1]
OK
[4 4 4 5]
OK
[5 7 0 8]
OK
[3 5]
OK
[0 7 8 4]
OK
[4 7 0 1]
OK
[2 8]
OK
[6 4 8 2]
OK
[1 1]
OK
[1 7 0 0]
OK
[7 0 3]
OK
[4 3 0 2]
OK
[7 8 7]
OK
[6 1]
OK
[4 5]
OK
[7 4 2]
OK
[0 1 1 6]
OK
[1 1]
OK
[7 6 3 3]
OK
[2 7 2]
OK
[5 5 3]
OK
[2 4]
OK
[3 1 4]
OK
[7 5 4 8]
OK
[4 1 4]
OK
[0 4]
OK
[6 8 6]
OK
[7 7 4 1]
OK
[6 5 5 0]
OK
[7 7 3 8]
OK
[3 6 6]
OK
[2 7 3]
OK
[7 0 3]
OK
[1 4 1 0]
OK

[2 2 4 6]
OK
[6 5 1 4]
OK
[6 2 3 7]
OK
[5 4 0]
OK
[3 5]
OK
[4 3]
OK
[2 5 8]
OK
[6 1 8 0]
OK
[5 5 4 1]
OK
[6 1 4 7]
OK
[7 7]
OK
[6 3 2 3]
OK
[1 7 8 1]
OK
[1 7 4]
OK
[7 1 2 0]
OK
[4 6]
OK
[7 3 5]
OK
[8 3 7]
OK
[6 2 5 8]
OK
[2 3 3 6]
OK
[1 3]
OK
[2 7]
OK
[1 3 2 0]
OK
[8 8 2 6]
OK
[1 0 3]
OK
[5 5]
OK
[4 1 0]
OK
[5 3]
OK
[5 2 1 1]
OK
[2 8]
OK
[6 6]
OK
[6 2 6 1]
OK
[1 1 6 5]
OK
[5 0 4 5]
OK
[3 6 1 2]
OK
[0 4 4]
OK
[4 1 2 3]
OK
[4 4]
OK
[6 3]
OK
[1 4 1]
OK
[8 8 5]
OK
[7 5 4]
OK
[4 3 7]
OK
[1 0 3 0]
OK
[0 4]
OK
[4 2 8 7]
OK
[4 8 8 4]
OK
[2 0 6]
OK
[4 1]
OK
[6 8 2]
OK
[3 1 4]
OK
[8 1 7 0]
OK
[2 2 2 4]
OK
[3 8 3]
OK
[8 1]
OK
[5 0 3 7]
OK
[6 5 2 4]
OK
[2 6 8 7]
OK
[6 8]
OK
[1 4]
OK
[1 2]
OK
[3 8 1]
OK
[5 2 4]
OK
[1 1 3]
OK
[0 6 7]
OK
[4 5 6]
OK
[7 3]
OK
[8 5 5]
OK
[1 7 5]
OK
[7 7]
OK
[5 5]
OK
[0 4]
OK
[0 6 8 5]
OK
[3 8 6]
OK
[2 5]
OK
[2 6]
OK
[0 6 7 1]
OK
[7 6 7]
OK
[3 1]
OK
[5 0]
OK
[5 1 1]
OK
[5 8 1 0]
OK
[7 3 7]
OK
[8 4]
OK
[1 3]
OK
[1 3 8 6]
OK
[8 6 7]
OK
[7 5 7 7]
OK
[5 6]
OK
[7 2]
OK
[8 6 2

OK
[4 5 0 3]
OK
[6 8]
OK
[4 6 6 8]
OK
[5 1 7 0]
OK
[6 1 0 6]
OK
[0 5 3 0]
OK
[8 2 8]
OK
[8 0 0]
OK
[0 0 1 4]
OK
[1 8 8 0]
OK
[4 5 3]
OK
[5 0 8]
OK
[0 6]
OK
[7 8 4 4]
OK
[7 1 3 0]
OK
[0 6]
OK
[1 8]
OK
[4 1 8 4]
OK
[5 8 2 1]
OK
[5 6 7]
OK
[8 5 4]
OK
[2 6 8]
OK
[7 3 2]
OK
[3 4 8 1]
OK
[7 8 2]
OK
[7 7 1]
OK
[0 7 5]
OK
[1 8 1]
OK
[1 7 2 3]
OK
[8 4]
OK
[3 0 4 4]
OK
[5 5 1]
OK
[4 0 2 7]
OK
[6 1 1]
OK
[3 0 1 1]
OK
[8 4 5 5]
OK
[0 4 1]
OK
[1 4 2]
OK
[0 5 8]
OK
[3 6]
OK
[8 4 1 8]
OK
[3 2 7 7]
OK
[3 0 2 3]
OK
[7 6 4]
OK
[7 4]
OK
[8 0 0]
OK
[3 6 0]
OK
[3 3]
OK
[1 7]
OK
[0 6 7 4]
OK
[0 7]
OK
[2 2]
OK
[6 0]
OK
[6 7 5 0]
OK
[5 6 4 1]
OK
[4 7 1 1]
OK
[8 4]
OK
[2 4 0]
OK
[0 2 4 6]
OK
[0 7 5 0]
OK
[6 2]
OK
[7 7]
OK
[1 6 3 7]
OK
[4 3]
OK
[3 3]
OK
[7 6]
OK
[4 0 0]
OK
[2 7 2 4]
OK
[3 8]
OK
[7 6]
OK
[3 2]
OK
[2 2 5 6]
OK
[2 1]
OK
[7 3 0]
OK
[1 4 8]
OK
[3 2 1]
OK
[3 4 8]
OK
[7 4 1 1]
OK
[3 0 7 0]
OK
[7 3]
OK
[2 2 1 7]
OK
[1 1 7]
OK
[3 4 7 1]
OK
[2 4 2]
OK
[5 1]
OK
[8 8 1 3]
OK
[1 7 4]
OK
[1 0 2]
OK
[8 1 8]
O

OK
[0 6]
OK
[7 8 7]
OK
[3 8]
OK
[2 3 1]
OK
[3 3]
OK
[5 8 2 2]
OK
[7 1]
OK
[3 6 4]
OK
[7 7 0 4]
OK
[4 1 6]
OK
[8 5 5]
OK
[4 7 7]
OK
[0 1]
OK
[3 0 0 1]
OK
[8 4 0 0]
OK
[8 2]
OK
[1 4 3 8]
OK
[1 6 1]
OK
[5 3]
OK
[6 0 5]
OK
[4 7]
OK
[5 6]
OK
[4 7]
OK
[4 3]
OK
[2 0]
OK
[8 3 7]
OK
[7 1 0 3]
OK
[3 0 8]
OK
[4 8]
OK
[7 4 3]
OK
[1 6 6 7]
OK
[5 3 7 1]
OK
[7 2 5 5]
OK
[3 1 6]
OK
[3 8 5 5]
OK
[0 3]
OK
[1 3 8 8]
OK
[0 8 8 5]
OK
[6 4]
OK
[8 2]
OK
[3 5 7]
OK
[7 3 1 7]
OK
[3 2 6 2]
OK
[3 6 1]
OK
[8 3 4]
OK
[5 5 2]
OK
[5 8 2]
OK
[0 8 8 0]
OK
[2 0 8 5]
OK
[8 3 6 2]
OK
[2 5]
OK
[7 4]
OK
[1 8 5 8]
OK
[2 7 4]
OK
[3 0]
OK
[5 8]
OK
[0 5]
OK
[4 2 1 4]
OK
[8 4 6]
OK
[2 3 5 1]
OK
[2 3]
OK
[2 3 1 3]
OK
[2 2 1 4]
OK
[8 2 4 2]
OK
[8 2]
OK
[7 8 7]
OK
[0 2]
OK
[7 5]
OK
[3 3 0]
OK
[4 4]
OK
[7 2 7 7]
OK
[3 3 3 2]
OK
[3 0]
OK
[5 5 7]
OK
[8 0 0 0]
OK
[4 6]
OK
[2 5]
OK
[6 1 2 0]
OK
[2 7]
OK
[6 0 0 2]
OK
[2 0 8 5]
OK
[1 5 7 7]
OK
[4 1 0]
OK
[0 7 6]
OK
[6 3]
OK
[7 6 6]
OK
[8 4 2]
OK
[2 2 7]
OK
[6 2]
OK
[8 3 3]
OK
[4 7]
OK
[8

OK
[5 5]
OK
[3 1 8 0]
OK
[8 1 4 3]
OK
[5 5 3]
OK
[4 8]
OK
[5 4 5 5]
OK
[8 6]
OK
[4 7]
OK
[4 8 8]
OK
[2 4 6]
OK
[0 6]
OK
[5 3 3]
OK
[8 8 5 7]
OK
[4 8]
OK
[8 3 2]
OK
[6 0 3]
OK
[8 2 7 1]
OK
[5 5 8]
OK
[2 5]
OK
[6 0 1 3]
OK
[5 5]
OK
[5 6]
OK
[7 0 7 4]
OK
[5 1 4]
OK
[7 8 6 8]
OK
[1 4 0]
OK
[8 4]
OK
[1 0]
OK
[5 2 3 8]
OK
[2 0 8 1]
OK
[2 8]
OK
[3 6 6]
OK
[5 2 3]
OK
[5 2]
OK
[1 4 7 6]
OK
[8 7 8 8]
OK
[3 6 4 5]
OK
[4 4]
OK
[8 1]
OK
[2 5]
OK
[0 8]
OK
[2 7 1]
OK
[3 1]
OK
[0 3]
OK
[1 0 6 8]
OK
[6 8 6]
OK
[5 5 2]
OK
[5 0]
OK
[2 6 5 4]
OK
[7 3 2]
OK
[2 8]
OK
[6 8 8]
OK
[7 0 6 0]
OK
[4 7 2 7]
OK
[4 2 7]
OK
[7 0 4]
OK
[5 1 1 4]
OK
[0 0]
OK
[3 5]
OK
[0 2 1]
OK
[6 7 8]
OK
[4 8 3]
OK
[0 2 4]
OK
[4 4]
OK
[2 2 8]
OK
[1 8 3]
OK
[5 0]
OK
[5 2 2]
OK
[8 3 1]
OK
[7 8 5 1]
OK
[7 2 5]
OK
[7 1 3]
OK
[1 5 2 2]
OK
[5 2 6 3]
OK
[6 3]
OK
[8 7 3 5]
OK
[7 7 8 0]
OK
[3 1 6]
OK
[7 1 4]
OK
[4 5 8]
OK
[8 6 1 8]
OK
[1 2 6 1]
OK
[8 5]
OK
[3 3 3 4]
OK
[8 7]
OK
[5 5]
OK
[2 2 8]
OK
[2 5]
OK
[5 3]
OK
[1 8 0]
OK
[5 3 5 4]
OK
[1 0

OK
[4 0]
OK
[2 4]
OK
[1 8 1]
OK
[8 7 3]
OK
[5 2]
OK
[1 6 4]
OK
[6 0 0]
OK
[1 2 6]
OK
[8 5]
OK
[8 3]
OK
[4 6]
OK
[7 8 1 8]
OK
[7 3 3 5]
OK
[6 0]
OK
[4 1 4 3]
OK
[4 7]
OK
[7 3 2 6]
OK
[0 2]
OK
[8 1]
OK
[8 1 8]
OK
[1 8 3 0]
OK
[5 7]
OK
[6 7 1]
OK
[4 5 7]
OK
[3 1 1 6]
OK
[2 2 3]
OK
[8 6 1 4]
OK
[2 3 5]
OK
[0 0 2]
OK
[7 7 4]
OK
[0 0 0]
OK
[3 8]
OK
[0 8 2]
OK
[0 3]
OK
[5 5]
OK
[3 0 4]
OK
[5 1 7]
OK
[6 2]
OK
[4 1]
OK
[0 1 8]
OK
[0 3]
OK
[2 4 6]
OK
[5 1]
OK
[7 6 2]
OK
[2 4 4 5]
OK
[3 5]
OK
[3 0 2]
OK
[8 4 4]
OK
[3 0 7]
OK
[4 7 2]
OK
[6 8]
OK
[8 7 1 8]
OK
[5 2 8 6]
OK
[1 0]
OK
[6 5 6]
OK
[2 7 2]
OK
[8 5]
OK
[5 3 4 1]
OK
[7 6]
OK
[0 4 5]
OK
[4 3 3 4]
OK
[4 6]
OK
[8 1]
OK
[0 4 8 7]
OK
[3 3 0 0]
OK
[5 6 4 5]
OK
[2 8]
OK
[3 7]
OK
[2 1]
OK
[7 8]
OK
[7 0]
OK
[7 2]
OK
[7 4]
OK
[3 4 2]
OK
[1 2]
OK
[7 1]
OK
[1 1 3 2]
OK
[1 2 0 2]
OK
[4 8 4 6]
OK
[5 4 3 5]
OK
[3 0 8]
OK
[5 6 6 8]
OK
[5 0 1 4]
OK
[2 0]
OK
[4 4]
OK
[7 3]
OK
[3 1 3 4]
OK
[2 8]
OK
[3 5 8]
OK
[5 8 1]
OK
[8 1 2]
OK
[1 5 2]
OK
[5 8 5]
OK
[7 0]


OK
[4 6 3]
OK
[5 4 3 4]
OK
[2 6 2]
OK
[5 2 2]
OK
[5 5]
OK
[6 5]
OK
[5 5 7 7]
OK
[3 2 1 4]
OK
[5 6]
OK
[3 6 8]
OK
[2 7 3]
OK
[1 7 0]
OK
[7 7 1 6]
OK
[8 0 5 8]
OK
[5 3 0]
OK
[5 8 6]
OK
[7 0 1 5]
OK
[0 8 8 7]
OK
[5 5 1 3]
OK
[7 6]
OK
[4 4 0 2]
OK
[8 3 4]
OK
[6 6 6 3]
OK
[4 5 1]
OK
[2 5 6]
OK
[0 5]
OK
[1 8 7]
OK
[1 4 4]
OK
[4 6 4 3]
OK
[6 1 6 3]
OK
[6 7 0 6]
OK
[0 0 3]
OK
[4 0 4 0]
OK
[6 0 5]
OK
[1 1]
OK
[7 1 0]
OK
[4 0]
OK
[6 6 3 7]
OK
[5 4 1 1]
OK
[5 8 1]
OK
[2 6 4]
OK
[2 0 5]
OK
[0 6 8]
OK
[7 7]
OK
[7 2]
OK
[2 1 4]
OK
[8 5]
OK
[7 0 3]
OK
[7 8 4]
OK
[8 7]
OK
[3 3]
OK
[0 2 7]
OK
[2 3 0]
OK
[8 5]
OK
[5 6]
OK
[0 7 4 2]
OK
[0 2]
OK
[8 5 0]
OK
[4 0 6]
OK
[5 5 4 2]
OK
[6 3]
OK
[8 6]
OK
[3 6 2]
OK
[6 2]
OK
[5 2 4]
OK
[6 0]
OK
[8 6 3]
OK
[4 0]
OK
[3 0 6 2]
OK
[5 5]
OK
[8 3 2 5]
OK
[3 8 5]
OK
[0 6 7]
OK
[7 4 6 6]
OK
[6 2 8 3]
OK
[4 1 2]
OK
[1 8]
OK
[2 5 0]
OK
[7 0]
OK
[0 1]
OK
[8 8 8 4]
OK
[8 2 6]
OK
[1 3 7]
OK
[7 0]
OK
[5 6 0 5]
OK
[2 3 4 0]
OK
[1 6]
OK
[7 4 6 0]
OK
[2 7 8 1]
OK
[2 3]
OK
[3 8 7]

OK
[6 1 7]
OK
[8 8 0]
OK
[7 4 6 1]
OK
[4 0 7]
OK
[8 4 3]
OK
[0 4 6]
OK
[3 5]
OK
[1 6 3 3]
OK
[3 0 0]
OK
[5 1 5]
OK
[5 0 5 3]
OK
[5 0 0]
OK
[0 4]
OK
[6 8]
OK
[4 0 2]
OK
[4 2]
OK
[3 7 5 1]
OK
[3 5 6 5]
OK
[0 5]
OK
[6 1]
OK
[2 7]
OK
[1 7 1]
OK
[8 6 1]
OK
[7 5 1 8]
OK
[4 7 3]
OK
[7 1 8]
OK
[6 2 5 5]
OK
[4 0 1]
OK
[6 4 6]
OK
[6 2]
OK
[4 0 7]
OK
[5 6]
OK
[7 3 3 7]
OK
[5 6 2]
OK
[4 1 8]
OK
[6 7 7 4]
OK
[3 5 8]
OK
[0 6]
OK
[3 2 1 4]
OK
[0 3 1 4]
OK
[1 6 6 5]
OK
[3 4]
OK
[5 0 1 4]
OK
[6 1]
OK
[5 5 0]
OK
[8 4 1 3]
OK
[5 5 8]
OK
[3 3 2]
OK
[3 0 3]
OK
[1 7]
OK
[1 3 0 0]
OK
[6 3 6 5]
OK
[6 2]
OK
[1 7 1 0]
OK
[5 4 8 3]
OK
[6 8]
OK
[6 0]
OK
[5 3]
OK
[7 6 0]
OK
[8 2]
OK
[6 8 5]
OK
[7 3]
OK
[5 3]
OK
[8 8 4 0]
OK
[5 7 8]
OK
[2 2 1]
OK
[6 5]
OK
[7 1 2]
OK
[0 4]
OK
[2 7 0 5]
OK
[2 3]
OK
[6 2 0 0]
OK
[1 0 4]
OK
[0 6]
OK
[5 7 7]
OK
[5 1 5 1]
OK
[4 4 2]
OK
[4 6 7 4]
OK
[3 2]
OK
[8 4 1]
OK
[2 6]
OK
[2 4]
OK
[3 2 5 5]
OK
[5 5 7]
OK
[0 1 0 2]
OK
[3 1 7]
OK
[4 0 3 8]
OK
[7 8 2 1]
OK
[8 1 1 7]
OK
[1 8 8 3]
OK
[2 

OK
[2 0 0 8]
OK
[4 2 6]
OK
[0 7 0 1]
OK
[7 8 6 6]
OK
[0 0 2 1]
OK
[4 6]
OK
[0 8]
OK
[5 3 8]
OK
[2 1 6]
OK
[0 2 2]
OK
[5 6]
OK
[5 3 0]
OK
[3 3 7 1]
OK
[5 5 4 5]
OK
[2 5 5]
OK
[5 3 4 1]
OK
[5 7]
OK
[2 8 7]
OK
[6 1]
OK
[8 8 5 2]
OK
[2 1 3 6]
OK
[0 3 0 2]
OK
[3 4 3]
OK
[8 3 8 3]
OK
[4 1 6 2]
OK
[7 8]
OK
[4 3]
OK
[5 3 8]
OK
[8 4 5]
OK
[2 8]
OK
[5 3 5 8]
OK
[7 3 7]
OK
[4 4]
OK
[7 7]
OK
[6 0 5]
OK
[8 0 6 0]
OK
[3 8 2 3]
OK
[0 7 8]
OK
[8 4 6]
OK
[5 1 7]
OK
[0 2 3 0]
OK
[2 5 4 5]
OK
[6 1 5 1]
OK
[8 4 7 0]
OK
[5 1 7]
OK
[2 1]
OK
[0 5 1]
OK
[2 8 2 6]
OK
[8 6]
OK
[6 8]
OK
[1 4]
OK
[2 4 8 2]
OK
[3 1]
OK
[3 4 3]
OK
[4 4 0]
OK
[4 0 2]
OK
[6 4 3 3]
OK
[6 4 8]
OK
[8 2]
OK
[0 7 7 1]
OK
[3 1 0 3]
OK
[6 2 8 0]
OK
[3 7 6]
OK
[1 6 8]
OK
[7 1 6 2]
OK
[6 4 3]
OK
[1 2 0]
OK
[4 7 3]
OK
[2 5 4 5]
OK
[3 8 4]
OK
[4 2 8]
OK
[7 7]
OK
[6 2]
OK
[7 0 5 0]
OK
[1 4 1 5]
OK
[0 2]
OK
[6 4 5]
OK
[0 6 2 3]
OK
[1 6 8]
OK
[0 4 2]
OK
[8 1 2]
OK
[7 3]
OK
[1 3]
OK
[4 2 5]
OK
[3 6 3 4]
OK
[7 2]
OK
[5 4]
OK
[3 7]
OK
[2 7 5 1]
OK
[7

[0 7 4 6]
OK
[3 2 6 5]
OK
[2 8]
OK
[0 0]
OK
[2 2]
OK
[7 4]
OK
[3 1 0]
OK
[1 8 0]
OK
[2 1 6]
OK
[1 0 4 2]
OK
[0 7 5]
OK
[1 8 0 2]
OK
[2 0 2]
OK
[3 7 5 8]
OK
[6 6]
OK
[8 3 7]
OK
[6 8 2]
OK
[1 3]
OK
[8 7]
OK
[1 2]
OK
[5 8 0]
OK
[7 3 4]
OK
[6 5 1]
OK
[1 6]
OK
[5 4 0]
OK
[8 8 1]
OK
[2 3 3]
OK
[0 4 3 8]
OK
[0 3 8]
OK
[0 3]
OK
[4 0 6]
OK
[2 5]
OK
[2 3]
OK
[6 3 6]
OK
[6 7]
OK
[5 8 2 0]
OK
[3 7 1]
OK
[0 3 8]
OK
[7 6]
OK
[7 6]
OK
[6 2 6]
OK
[6 5 3 4]
OK
[7 4]
OK
[6 3]
OK
[3 6]
OK
[6 3 1 0]
OK
[0 3]
OK
[4 2]
OK
[4 2 2 4]
OK
[6 4]
OK
[1 5]
OK
[5 2]
OK
[7 0 4]
OK
[1 7 2]
OK
[2 1 6]
OK
[1 0]
OK
[7 2]
OK
[3 3]
OK
[4 1 0 5]
OK
[5 4 8 6]
OK
[2 7]
OK
[6 8]
OK
[3 3 6]
OK
[1 4 0 5]
OK
[7 8 4 1]
OK
[4 8]
OK
[3 1 8]
OK
[4 2 1]
OK
[2 3 0]
OK
[8 6 8 2]
OK
[0 6]
OK
[7 8 1 7]
OK
[3 5 8 5]
OK
[4 1]
OK
[4 8 6 3]
OK
[7 3 2 0]
OK
[1 3 1 6]
OK
[7 7]
OK
[2 0 7]
OK
[5 6]
OK
[8 3 5 0]
OK
[3 8 7 7]
OK
[4 2]
OK
[1 7 1]
OK
[0 0 5]
OK
[0 7]
OK
[3 4 4 1]
OK
[4 5]
OK
[4 5 8]
OK
[0 0 3]
OK
[3 0 8 4]
OK
[4 0 8]
OK
[3 7 7]
OK
[

OK
[0 5 2 4]
OK
[5 4 7]
OK
[4 3 6]
OK
[7 7 4]
OK
[5 4 4]
OK
[4 1 1]
OK
[1 8]
OK
[8 3]
OK
[1 2]
OK
[7 6 1]
OK
[1 0 6]
OK
[6 5 1 7]
OK
[1 7 6]
OK
[7 5]
OK
[0 6 3 3]
OK
[7 1]
OK
[0 3]
OK
[0 4 0 1]
OK
[1 1 7]
OK
[3 7]
OK
[2 4 6]
OK
[4 3]
OK
[4 6 5 6]
OK
[3 1]
OK
[5 0]
OK
[5 4]
OK
[7 1 3 0]
OK
[2 6]
OK
[0 3 6 1]
OK
[5 2]
OK
[8 1]
OK
[7 1 0]
OK
[1 2 5]
OK
[5 3]
OK
[6 8 6]
OK
[2 1 0]
OK
[2 0 1]
OK
[5 2 6 3]
OK
[2 3 4 8]
OK
[2 5]
OK
[0 2]
OK
[1 7 7 4]
OK
[2 0 3]
OK
[4 3 1 3]
OK
[1 3 0]
OK
[0 5 4]
OK
[5 1 4]
OK
[7 4 0 7]
OK
[2 0 1 1]
OK
[6 1 3]
OK
[1 7 1 1]
OK
[2 5]
OK
[0 8 7 4]
OK
[5 6 6 4]
OK
[7 1 3 4]
OK
[5 8 4 4]
OK
[4 4 2]
OK
[0 4 1 8]
OK
[6 0 4]
OK
[0 5 8]
OK
[1 2 3]
OK
[2 1 4 6]
OK
[5 5 1 7]
OK
[4 5]
OK
[7 5 0 7]
OK
[2 8 0]
OK
[0 0 7 6]
OK
[2 1 6]
OK
[1 6 2 6]
OK
[7 1]
OK
[3 4 8]
OK
[4 2 4]
OK
[8 0]
OK
[1 0]
OK
[0 3]
OK
[8 8]
OK
[2 3 0 0]
OK
[5 6 0]
OK
[8 7 4 2]
OK
[6 1 2]
OK
[4 7]
OK
[3 4 1]
OK
[7 1 0 6]
OK
[3 1 7 8]
OK
[1 0]
OK
[0 8]
OK
[3 7 4 0]
OK
[8 3 6]
OK
[8 7]
OK
[2 2]
OK
[0 4 2]

[3 3 8 5]
OK
[7 0]
OK
[3 2]
OK
[7 2]
OK
[8 0 6 1]
OK
[7 2]
OK
[8 1 5 0]
OK
[6 5 5]
OK
[0 7]
OK
[4 3]
OK
[3 8 4]
OK
[2 5 1 5]
OK
[7 5]
OK
[2 1 1]
OK
[1 3 6 6]
OK
[5 3]
OK
[3 7]
OK
[0 5]
OK
[3 3 7]
OK
[1 8 8 8]
OK
[0 6 1]
OK
[5 0 1]
OK
[0 7]
OK
[7 0]
OK
[6 5]
OK
[1 8 4]
OK
[1 5 3]
OK
[2 5 0 3]
OK
[2 5 3]
OK
[8 1]
OK
[2 0 2]
OK
[8 0 2 1]
OK
[1 2]
OK
[4 6 1]
OK
[4 5 2 3]
OK
[3 6]
OK
[3 7]
OK
[0 7 1]
OK
[8 8]
OK
[5 2 4 6]
OK
[2 2 4 4]
OK
[3 3]
OK
[4 7 6 0]
OK
[3 8 1]
OK
[5 6]
OK
[5 7 2 1]
OK
[6 2]
OK
[0 6]
OK
[1 8 6]
OK
[2 6 6]
OK
[3 8 1 3]
OK
[0 3 5]
OK
[7 7 5 4]
OK
[5 2 7 3]
OK
[3 8 1]
OK
[1 3]
OK
[7 4 4 0]
OK
[2 7 3 2]
OK
[1 1]
OK
[3 2]
OK
[4 4]
OK
[2 0 6]
OK
[2 3]
OK
[1 6]
OK
[6 8 4]
OK
[5 0 1 3]
OK
[2 5]
OK
[4 3 1 6]
OK
[7 5 3]
OK
[4 1]
OK
[8 7 4 7]
OK
[6 8 7]
OK
[4 6]
OK
[8 8]
OK
[3 3]
OK
[0 7 7]
OK
[1 5 0 5]
OK
[6 7]
OK
[5 0]
OK
[3 3 4 6]
OK
[2 7 6]
OK
[5 4 5]
OK
[2 2 4]
OK
[6 8]
OK
[4 2 4 4]
OK
[1 3]
OK
[6 8]
OK
[6 5]
OK
[1 6 2]
OK
[5 7 0 7]
OK
[5 0]
OK
[1 8]
OK
[4 6 5 6]
OK
[8 3 8 

[4 1 0]
OK
[6 7 6]
OK
[1 6]
OK
[3 6 7 1]
OK
[5 0]
OK
[6 0]
OK
[6 4]
OK
[3 5 7 1]
OK
[7 1 7 7]
OK
[8 8 7 4]
OK
[3 6 2]
OK
[6 1]
OK
[2 6 5 5]
OK
[8 3 8 2]
OK
[1 2 6]
OK
[2 1 0]
OK
[5 7 5]
OK
[4 0 8 5]
OK
[0 3 7 6]
OK
[0 7]
OK
[5 5 5]
OK
[7 2 8]
OK
[5 3]
OK
[4 3 3 4]
OK
[7 2 4 5]
OK
[0 7 4 6]
OK
[6 7 1]
OK
[7 6 2]
OK
[6 3 8]
OK
[1 2]
OK
[7 3 6 5]
OK
[2 0 7]
OK
[5 5 0 3]
OK
[4 6]
OK
[2 2 3 3]
OK
[8 2]
OK
[8 7]
OK
[7 2]
OK
[3 7 7 1]
OK
[5 6]
OK
[0 7 2 2]
OK
[3 8 7]
OK
[6 5]
OK
[6 8]
OK
[8 3 1]
OK
[0 6]
OK
[4 8 8 6]
OK
[2 0 4]
OK
[3 0 7 4]
OK
[4 6]
OK
[3 6 2]
OK
[7 7 2]
OK
[1 4]
OK
[6 5]
OK
[1 7 0]
OK
[2 3 8 6]
OK
[1 1 1 3]
OK
[3 8 6]
OK
[6 1 4 6]
OK
[2 6 5 6]
OK
[3 0]
OK
[5 3]
OK
[7 8 1]
OK
[7 0 4]
OK
[6 2 5 5]
OK
[6 8 1 6]
OK
[7 1]
OK
[2 1 3]
OK
[0 8 1]
OK
[7 0]
OK
[2 1]
OK
[4 0 2 2]
OK
[8 5]
OK
[6 0 4 7]
OK
[5 4]
OK
[7 6]
OK
[6 6 2 1]
OK
[5 3 8 5]
OK
[4 3]
OK
[2 5 5 5]
OK
[3 7 6 0]
OK
[0 6 7]
OK
[6 6 8 6]
OK
[7 3 1 3]
OK
[8 8]
OK
[5 5]
OK
[7 7 8 7]
OK
[7 0 5 0]
OK
[4 2 5]
OK
[0 6]
OK
[5 6

OK
[4 3 0]
OK
[1 6]
OK
[5 5 6 2]
OK
[6 8 6 7]
OK
[4 6 2 6]
OK
[7 4 6]
OK
[1 7]
OK
[5 2]
OK
[7 7 4 4]
OK
[4 2 7 0]
OK
[6 8]
OK
[3 1 3 8]
OK
[6 4 6 1]
OK
[4 4 6]
OK
[6 4 8 7]
OK
[7 7 6]
OK
[6 7 7]
OK
[2 8 4 5]
OK
[6 3 8 2]
OK
[1 8 0]
OK
[6 7]
OK
[5 2 6]
OK
[7 7 0 5]
OK
[2 1]
OK
[4 2]
OK
[8 8 0]
OK
[1 3 2 5]
OK
[7 6 1 8]
OK
[8 0 6]
OK
[8 6 5 0]
OK
[0 8 1 8]
OK
[2 8]
OK
[7 1 6]
OK
[6 5 1]
OK
[6 7 3]
OK
[2 7]
OK
[0 1 6]
OK
[5 4]
OK
[5 1]
OK
[5 6 7]
OK
[6 5 7]
OK
[5 4]
OK
[5 6 4 1]
OK
[4 8 5]
OK
[4 3 3 8]
OK
[8 2 5]
OK
[6 6 7 5]
OK
[5 0 3 1]
OK
[4 6 4]
OK
[5 8 6]
OK
[3 6 5 2]
OK
[6 8 6]
OK
[5 3]
OK
[0 6 1 6]
OK
[2 3]
OK
[0 4 5 0]
OK
[4 8 0]
OK
[0 2 4 0]
OK
[6 1 5 6]
OK
[0 0 2]
OK
[8 6 0 8]
OK
[4 4]
OK
[0 4 6]
OK
[8 4 3]
OK
[0 6 5 7]
OK
[6 7 3]
OK
[1 2 4 1]
OK
[1 4 2]
OK
[4 1 4]
OK
[4 8]
OK
[7 4]
OK
[2 1 2 2]
OK
[1 1 3]
OK
[4 3 4]
OK
[2 8 8 6]
OK
[2 7]
OK
[8 8 1 5]
OK
[4 1 6 5]
OK
[7 7 6 4]
OK
[2 6 7 4]
OK
[5 0 4]
OK
[7 5]
OK
[3 1 8]
OK
[1 3]
OK
[8 2 3 5]
OK
[2 2]
OK
[5 8 8]
OK
[3 7 3]
OK
[1 

[5 2 6]
OK
[5 0 1]
OK
[7 5 1 2]
OK
[3 6 6 0]
OK
[7 7]
OK
[4 7]
OK
[5 2]
OK
[1 1 0]
OK
[3 7]
OK
[3 8 6 6]
OK
[6 7]
OK
[1 8 6 0]
OK
[3 3 2]
OK
[3 1]
OK
[7 1]
OK
[5 1 1 0]
OK
[7 7 6 5]
OK
[5 5]
OK
[5 7 6 0]
OK
[7 0]
OK
[1 8 2 3]
OK
[7 2 4 1]
OK
[7 7]
OK
[4 4]
OK
[5 7 0 8]
OK
[5 0 5 3]
OK
[3 7]
OK
[8 7 1]
OK
[3 1 0]
OK
[5 2 2]
OK
[5 8 0 6]
OK
[3 1 5 6]
OK
[5 7 5]
OK
[2 3 2]
OK
[5 8 4]
OK
[3 3]
OK
[0 0]
OK
[5 2 5 3]
OK
[3 8]
OK
[4 5 3 7]
OK
[4 7 6]
OK
[1 6 1]
OK
[4 2]
OK
[2 0]
OK
[8 5 4]
OK
[8 0]
OK
[2 2 3 0]
OK
[0 8]
OK
[2 2 4 4]
OK
[1 0 0]
OK
[6 0 1]
OK
[4 4 5]
OK
[0 4 6]
OK
[3 3 6 2]
OK
[8 4 8 0]
OK
[1 6 6]
OK
[5 3 6 6]
OK
[2 3]
OK
[2 2]
OK
[6 5 0]
OK
[4 6 2]
OK
[2 4]
OK
[1 6]
OK
[5 3 4]
OK
[7 6]
OK
[3 3 8 6]
OK
[1 6]
OK
[4 3 4]
OK
[0 3 6]
OK
[4 3]
OK
[0 5 7 5]
OK
[3 0 8 6]
OK
[3 0 7]
OK
[8 6 1]
OK
[8 2]
OK
[7 2 5 6]
OK
[8 3 0]
OK
[2 5 2 5]
OK
[5 4 5]
OK
[2 4 3]
OK
[5 4 5 0]
OK
[3 0 1]
OK
[6 0]
OK
[8 3]
OK
[2 8 5]
OK
[0 0]
OK
[5 4 2]
OK
[5 0 1]
OK
[1 8]
OK
[5 3]
OK
[0 6]
OK
[1 6 4]
OK
[4

KeyboardInterrupt: 

In [149]:
pairwise_product_fast([8, 6, 8, 6])

0 1


64